// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Yakkomom.Data;

#nullable disable

namespace Yakkomom.Data.Migrations
{
    [DbContext(typeof(YakkomomDbContext))]
    [Migration("20260930143614_AuthentificationAdmin")]
    partial class AuthentificationAdmin
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("terrain_reference_seq");

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text")
                        .HasColumnName("friendly_name");

                    b.Property<string>("Xml")
                        .HasColumnType("text")
                        .HasColumnName("xml");

                    b.HasKey("Id")
                        .HasName("pk_data_protection_keys");

                    b.ToTable("data_protection_keys", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_role_claims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_role_claims_role_id");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_claims_user_id");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_asp_net_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_logins_user_id");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<string>("RoleId")
                        .HasColumnType("text")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_asp_net_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_user_roles_role_id");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_asp_net_user_tokens");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Yakkomom.Models.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTime>("CreeLe")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cree_le");

                    b.Property<DateTime?>("DerniereConnexion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("derniere_connexion");

                    b.Property<bool>("DoitChangerMotDePasse")
                        .HasColumnType("boolean")
                        .HasColumnName("doit_changer_mot_de_passe");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NomComplet")
                        .HasColumnType("text")
                        .HasColumnName("nom_complet");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_users");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Yakkomom.Models.Entities.ClicWhatsApp", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<short>("NumeroIndex")
                        .HasColumnType("smallint")
                        .HasColumnName("numero_index");

                    b.Property<int?>("ServiceId")
                        .HasColumnType("integer")
                        .HasColumnName("service_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("source");

                    b.Property<int?>("TerrainId")
                        .HasColumnType("integer")
                        .HasColumnName("terrain_id");

                    b.HasKey("Id")
                        .HasName("pk_clics_whatsapp");

                    b.HasIndex("Date")
                        .HasDatabaseName("ix_clics_whatsapp_date");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("ix_clics_whatsapp_service_id");

                    b.HasIndex("TerrainId", "Date")
                        .HasDatabaseName("ix_clics_whatsapp_terrain_id_date");

                    b.ToTable("clics_whatsapp", (string)null);
                });

            modelBuilder.Entity("Yakkomom.Models.Entities.DocumentFoncier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CleStockage")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("cle_stockage");

                    b.Property<DateTime>("CreeLe")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cree_le");

                    b.Property<string>("CreeParId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("cree_par_id");

                    b.Property<bool>("EstPublic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("est_public");

                    b.Property<string>("NomFichierOriginal")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nom_fichier_original");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<long>("TailleOctets")
                        .HasColumnType("bigint")
                        .HasColumnName("taille_octets");

                    b.Property<int>("TerrainId")
                        .HasColumnType("integer")
                        .HasColumnName("terrain_id");

                    b.Property<string>("Titre")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("titre");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("type");

                    b.Property<string>("TypeMime")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("type_mime");

                    b.HasKey("Id")
                        .HasName("pk_documents_fonciers");

                    b.HasIndex("TerrainId", "Type")
                        .HasDatabaseName("ix_documents_fonciers_terrain_id_type");

                    b.ToTable("documents_fonciers", (string)null);
                });

            modelBuilder.Entity("Yakkomom.Models.Entities.Hotspot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("PanoramaCibleId")
                        .HasColumnType("integer")
                        .HasColumnName("panorama_cible_id");

                    b.Property<int>("PanoramaId")
                        .HasColumnType("integer")
                        .HasColumnName("panorama_id");

                    b.Property<double>("Pitch")
                        .HasColumnType("double precision")
                        .HasColumnName("pitch");

                    b.Property<string>("Texte")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("texte");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("type");

                    b.Property<double>("Yaw")
                        .HasColumnType("double precision")
                        .HasColumnName("yaw");

                    b.HasKey("Id")
                        .HasName("pk_hotspots");

                    b.HasIndex("PanoramaCibleId")
                        .HasDatabaseName("ix_hotspots_panorama_cible_id");

                    b.HasIndex("PanoramaId")
                        .HasDatabaseName("ix_hotspots_panorama_id");

                    b.ToTable("hotspots", (string)null);
                });

            modelBuilder.Entity("Yakkomom.Models.Entities.JournalAction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("action");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("DetailsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("details_json");

                    b.Property<string>("EntiteId")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("entite_id");

                    b.Property<string>("EntiteType")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("entite_type");

                    b.Property<string>("UtilisateurId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("utilisateur_id");

                    b.Property<string>("UtilisateurNom")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("utilisateur_nom");

                    b.HasKey("Id")
                        .HasName("pk_journal_actions");

                    b.HasIndex("Date")
                        .HasDatabaseName("ix_journal_actions_date");

                    b.HasIndex("EntiteType", "EntiteId")
                        .HasDatabaseName("ix_journal_actions_entite_type_entite_id");

                    b.ToTable("journal_actions", (string)null);
                });

            modelBuilder.Entity("Yakkomom.Models.Entities.Localite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("EstActive")
                        .HasColumnType("boolean")
                        .HasColumnName("est_active");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nom");

                    b.Property<int>("Ordre")
                        .HasColumnType("integer")
                        .HasColumnName("ordre");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer")
                        .HasColumnName("parent_id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("character varying(140)")
                        .HasColumnName("slug");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_localites");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_localites_parent_id");

                    b.HasIndex("Type", "ParentId", "Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_localites_type_parent_id_slug");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("Type", "ParentId", "Slug"), false);

                    b.ToTable("localites", (string)null);
                });

            modelBuilder.Entity("Yakkomom.Models.Entities.Panorama", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CleStockageBd")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("cle_stockage_bd");

                    b.Property<string>("CleStockageHd")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("cle_stockage_hd");

                    b.Property<string>("CleVignette")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("cle_vignette");

                    b.Property<DateTime>("CreeLe")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cree_le");

                    b.Property<bool>("EstDepart")
                        .HasColumnType("boolean")
                        .HasColumnName("est_depart");

                    b.Property<double>("HfovInitial")
                        .HasColumnType("double precision")
                        .HasColumnName("hfov_initial");

                    b.Property<int>("Ordre")
                        .HasColumnType("integer")
                        .HasColumnName("ordre");

                    b.Property<double>("PitchInitial")
                        .HasColumnType("double precision")
                        .HasColumnName("pitch_initial");

                    b.Property<long>("TailleOctetsBd")
                        .HasColumnType("bigint")
                        .HasColumnName("taille_octets_bd");

                    b.Property<long>("TailleOctetsHd")
                        .HasColumnType("bigint")
                        .HasColumnName("taille_octets_hd");

                    b.Property<int>("TerrainId")
                        .HasColumnType("integer")
                        .HasColumnName("terrain_id");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("titre");

                    b.Property<double>("YawInitial")
                        .HasColumnType("double precision")
                        .HasColumnName("yaw_initial");

                    b.HasKey("Id")
                        .HasName("pk_panoramas");

                    b.HasIndex("TerrainId")
                        .IsUnique()
                        .HasDatabaseName("ix_panoramas_depart_unique")
                        .HasFilter("est_depart");

                    b.HasIndex("TerrainId", "Ordre")
                        .HasDatabaseName("ix_panoramas_terrain_id_ordre");

                    b.ToTable("panoramas", (string)null);
                });

            modelBuilder.Entity("Yakkomom.Models.Entities.ParametreSite", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Adresse")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("adresse");

                    b.Property<string>("CleLogo")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("cle_logo");

                    b.Property<string>("Facebook")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("facebook");

                    b.Property<string>("HorairesOuverture")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("horaires_ouverture");

                    b.Property<string>("Instagram")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("instagram");

                    b.Property<string>("LinkedIn")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("linked_in");

                    b.Property<string>("MessageWhatsAppTerrain")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("message_whats_app_terrain");

                    b.Property<DateTime>("ModifieLe")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modifie_le");

                    b.Property<string>("NomSite")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nom_site");

                    b.Property<string>("Slogan")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("slogan");

                    b.Property<string>("TikTok")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("tik_tok");

                    b.Property<string>("YouTube")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("you_tube");

                    b.HasKey("Id")
                        .HasName("pk_parametres_site");

                    b.ToTable("parametres_site", (string)null);
                });

            modelBuilder.Entity("Yakkomom.Models.Entities.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CleImageCouverture")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("cle_image_couverture");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("EstActif")
                        .HasColumnType("boolean")
                        .HasColumnName("est_actif");

                    b.Property<string>("Icone")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("icone");

                    b.Property<string>("MessageWhatsApp")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("message_whats_app");

                    b.Property<DateTime>("ModifieLe")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modifie_le");

                    b.Property<int>("Ordre")
                        .HasColumnType("integer")
                        .HasColumnName("ordre");

                    b.Property<string>("Resume")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("resume");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("character varying(140)")
                        .HasColumnName("slug");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("titre");

                    b.HasKey("Id")
                        .HasName("pk_services");

                    b.HasIndex("Ordre")
                        .HasDatabaseName("ix_services_ordre");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_services_slug");

                    b.ToTable("services", (string)null);
                });

            modelBuilder.Entity("Yakkomom.Models.Entities.ServicePhoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CleStockage")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("cle_stockage");

                    b.Property<string>("CouleurDominante")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("couleur_dominante");

                    b.Property<int>("Hauteur")
                        .HasColumnType("integer")
                        .HasColumnName("hauteur");

                    b.Property<int>("Largeur")
                        .HasColumnType("integer")
                        .HasColumnName("largeur");

                    b.Property<string>("Legende")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("legende");

                    b.Property<int>("Ordre")
                        .HasColumnType("integer")
                        .HasColumnName("ordre");

                    b.Property<int>("ServiceId")
                        .HasColumnType("integer")
                        .HasColumnName("service_id");

                    b.HasKey("Id")
                        .HasName("pk_service_photos");

                    b.HasIndex("ServiceId", "Ordre")
                        .HasDatabaseName("ix_service_photos_service_id_ordre");

                    b.ToTable("service_photos", (string)null);
                });

            modelBuilder.Entity("Yakkomom.Models.Entities.Terrain", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool?>("AccesEau")
                        .HasColumnType("boolean")
                        .HasColumnName("acces_eau");

                    b.Property<bool?>("AccesElectricite")
                        .HasColumnType("boolean")
                        .HasColumnName("acces_electricite");

                    b.Property<string>("Adresse")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("adresse");

                    b.Property<int?>("CommuneId")
                        .HasColumnType("integer")
                        .HasColumnName("commune_id");

                    b.Property<string>("ContourGeoJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("contour_geo_json");

                    b.Property<DateTime>("CreeLe")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cree_le");

                    b.Property<string>("CreeParId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("cree_par_id");

                    b.Property<int?>("DepartementId")
                        .HasColumnType("integer")
                        .HasColumnName("departement_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("EstMisEnAvant")
                        .HasColumnType("boolean")
                        .HasColumnName("est_mis_en_avant");

                    b.Property<decimal?>("LargeurM")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("largeur_m");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<decimal?>("LongueurM")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("longueur_m");

                    b.Property<DateTime>("ModifieLe")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modifie_le");

                    b.Property<string>("ModifieParId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("modifie_par_id");

                    b.Property<int>("OrdreMiseEnAvant")
                        .HasColumnType("integer")
                        .HasColumnName("ordre_mise_en_avant");

                    b.Property<long?>("Prix")
                        .HasColumnType("bigint")
                        .HasColumnName("prix");

                    b.Property<bool>("PrixNegociable")
                        .HasColumnType("boolean")
                        .HasColumnName("prix_negociable");

                    b.Property<DateTime?>("PublieLe")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("publie_le");

                    b.Property<string>("QuartierVillage")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("quartier_village");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("reference");

                    b.Property<int?>("RegionId")
                        .HasColumnType("integer")
                        .HasColumnName("region_id");

                    b.Property<bool?>("RouteAcces")
                        .HasColumnType("boolean")
                        .HasColumnName("route_acces");

                    b.Property<string>("RouteAccesDetail")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("route_acces_detail");

                    b.Property<string>("SituationFonciere")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("situation_fonciere");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("statut");

                    b.Property<decimal?>("SurfaceCalculeeM2")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("surface_calculee_m2");

                    b.Property<decimal?>("SurfaceM2")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("surface_m2");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("titre");

                    b.Property<string>("Type")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("type");

                    b.Property<string>("VideoYoutubeUrl")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("video_youtube_url");

                    b.HasKey("Id")
                        .HasName("pk_terrains");

                    b.HasIndex("CommuneId")
                        .HasDatabaseName("ix_terrains_commune_id");

                    b.HasIndex("DepartementId")
                        .HasDatabaseName("ix_terrains_departement_id");

                    b.HasIndex("Prix")
                        .HasDatabaseName("ix_terrains_prix");

                    b.HasIndex("PublieLe")
                        .HasDatabaseName("ix_terrains_publie_le");

                    b.HasIndex("Reference")
                        .IsUnique()
                        .HasDatabaseName("ix_terrains_reference");

                    b.HasIndex("RegionId")
                        .HasDatabaseName("ix_terrains_region_id");

                    b.HasIndex("Statut")
                        .HasDatabaseName("ix_terrains_statut");

                    b.HasIndex("SurfaceM2")
                        .HasDatabaseName("ix_terrains_surface_m2");

                    b.HasIndex("Type")
                        .HasDatabaseName("ix_terrains_type");

                    b.HasIndex("EstMisEnAvant", "OrdreMiseEnAvant")
                        .HasDatabaseName("ix_terrains_est_mis_en_avant_ordre_mise_en_avant");

                    b.ToTable("terrains", (string)null);
                });

            modelBuilder.Entity("Yakkomom.Models.Entities.TerrainPhoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CleStockage")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("cle_stockage");

                    b.Property<string>("CouleurDominante")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("couleur_dominante");

                    b.Property<DateTime>("CreeLe")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cree_le");

                    b.Property<bool>("EstCouverture")
                        .HasColumnType("boolean")
                        .HasColumnName("est_couverture");

                    b.Property<int>("Hauteur")
                        .HasColumnType("integer")
                        .HasColumnName("hauteur");

                    b.Property<int>("Largeur")
                        .HasColumnType("integer")
                        .HasColumnName("largeur");

                    b.Property<string>("Legende")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("legende");

                    b.Property<int>("Ordre")
                        .HasColumnType("integer")
                        .HasColumnName("ordre");

                    b.Property<long>("TailleOctets")
                        .HasColumnType("bigint")
                        .HasColumnName("taille_octets");

                    b.Property<int>("TerrainId")
                        .HasColumnType("integer")
                        .HasColumnName("terrain_id");

                    b.HasKey("Id")
                        .HasName("pk_terrain_photos");

                    b.HasIndex("TerrainId")
                        .IsUnique()
                        .HasDatabaseName("ix_terrain_photos_couverture_unique")
                        .HasFilter("est_couverture");

                    b.HasIndex("TerrainId", "Ordre")
                        .HasDatabaseName("ix_terrain_photos_terrain_id_ordre");

                    b.ToTable("terrain_photos", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_role_claims_asp_net_roles_role_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Yakkomom.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_claims_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Yakkomom.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_logins_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_roles_role_id");

                    b.HasOne("Yakkomom.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Yakkomom.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_tokens_asp_net_users_user_id");
                });

            modelBuilder.Entity("Yakkomom.Models.Entities.ClicWhatsApp", b =>
                {
                    b.HasOne("Yakkomom.Models.Entities.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_clics_whatsapp_services_service_id");

                    b.HasOne("Yakkomom.Models.Entities.Terrain", "Terrain")
                        .WithMany("ClicsWhatsApp")
                        .HasForeignKey("TerrainId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_clics_whatsapp_terrains_terrain_id");

                    b.Navigation("Service");

                    b.Navigation("Terrain");
                });

            modelBuilder.Entity("Yakkomom.Models.Entities.DocumentFoncier", b =>
                {
                    b.HasOne("Yakkomom.Models.Entities.Terrain", "Terrain")
                        .WithMany("Documents")
                        .HasForeignKey("TerrainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_documents_fonciers_terrains_terrain_id");

                    b.Navigation("Terrain");
                });

            modelBuilder.Entity("Yakkomom.Models.Entities.Hotspot", b =>
                {
                    b.HasOne("Yakkomom.Models.Entities.Panorama", "PanoramaCible")
                        .WithMany()
                        .HasForeignKey("PanoramaCibleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_hotspots_panoramas_panorama_cible_id");

                    b.HasOne("Yakkomom.Models.Entities.Panorama", "Panorama")
                        .WithMany("Hotspots")
                        .HasForeignKey("PanoramaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_hotspots_panoramas_panorama_id");

                    b.Navigation("Panorama");

                    b.Navigation("PanoramaCible");
                });

            modelBuilder.Entity("Yakkomom.Models.Entities.Localite", b =>
                {
                    b.HasOne("Yakkomom.Models.Entities.Localite", "Parent")
                        .WithMany("Enfants")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_localites_localites_parent_id");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Yakkomom.Models.Entities.Panorama", b =>
                {
                    b.HasOne("Yakkomom.Models.Entities.Terrain", "Terrain")
                        .WithMany("Panoramas")
                        .HasForeignKey("TerrainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_panoramas_terrains_terrain_id");

                    b.Navigation("Terrain");
                });

            modelBuilder.Entity("Yakkomom.Models.Entities.ParametreSite", b =>
                {
                    b.OwnsOne("Yakkomom.Models.Entities.Contact", "ContactsParDefaut", b1 =>
                        {
                            b1.Property<int>("ParametreSiteId")
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            b1.Property<string>("Email")
                                .HasMaxLength(254)
                                .HasColumnType("character varying(254)")
                                .HasColumnName("email");

                            b1.Property<string>("WhatsApp1")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("whatsapp1");

                            b1.Property<string>("WhatsApp1Libelle")
                                .HasMaxLength(60)
                                .HasColumnType("character varying(60)")
                                .HasColumnName("whatsapp1_libelle");

                            b1.Property<string>("WhatsApp2")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("whatsapp2");

                            b1.Property<string>("WhatsApp2Libelle")
                                .HasMaxLength(60)
                                .HasColumnType("character varying(60)")
                                .HasColumnName("whatsapp2_libelle");

                            b1.Property<string>("WhatsApp3")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("whatsapp3");

                            b1.Property<string>("WhatsApp3Libelle")
                                .HasMaxLength(60)
                                .HasColumnType("character varying(60)")
                                .HasColumnName("whatsapp3_libelle");

                            b1.HasKey("ParametreSiteId");

                            b1.ToTable("parametres_site");

                            b1.WithOwner()
                                .HasForeignKey("ParametreSiteId")
                                .HasConstraintName("fk_parametres_site_parametres_site_id");
                        });

                    b.Navigation("ContactsParDefaut")
                        .IsRequired();
                });

            modelBuilder.Entity("Yakkomom.Models.Entities.ServicePhoto", b =>
                {
                    b.HasOne("Yakkomom.Models.Entities.Service", "Service")
                        .WithMany("Photos")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_service_photos_services_service_id");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("Yakkomom.Models.Entities.Terrain", b =>
                {
                    b.HasOne("Yakkomom.Models.Entities.Localite", "Commune")
                        .WithMany()
                        .HasForeignKey("CommuneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_terrains_localites_commune_id");

                    b.HasOne("Yakkomom.Models.Entities.Localite", "Departement")
                        .WithMany()
                        .HasForeignKey("DepartementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_terrains_localites_departement_id");

                    b.HasOne("Yakkomom.Models.Entities.Localite", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_terrains_localites_region_id");

                    b.OwnsMany("Yakkomom.Models.Entities.Commodite", "Commodites", b1 =>
                        {
                            b1.Property<int>("TerrainId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<decimal?>("DistanceKm")
                                .HasPrecision(14, 2);

                            b1.Property<string>("Libelle")
                                .IsRequired()
                                .HasMaxLength(100);

                            b1.HasKey("TerrainId", "__synthesizedOrdinal")
                                .HasName("pk_terrains");

                            b1.ToTable("terrains");

                            b1
                                .ToJson("commodites")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("TerrainId")
                                .HasConstraintName("fk_terrains_terrains_terrain_id");
                        });

                    b.OwnsOne("Yakkomom.Models.Entities.Contact", "Contacts", b1 =>
                        {
                            b1.Property<int>("TerrainId")
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            b1.Property<string>("Email")
                                .HasMaxLength(254)
                                .HasColumnType("character varying(254)")
                                .HasColumnName("email");

                            b1.Property<string>("WhatsApp1")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("whatsapp1");

                            b1.Property<string>("WhatsApp1Libelle")
                                .HasMaxLength(60)
                                .HasColumnType("character varying(60)")
                                .HasColumnName("whatsapp1_libelle");

                            b1.Property<string>("WhatsApp2")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("whatsapp2");

                            b1.Property<string>("WhatsApp2Libelle")
                                .HasMaxLength(60)
                                .HasColumnType("character varying(60)")
                                .HasColumnName("whatsapp2_libelle");

                            b1.Property<string>("WhatsApp3")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("whatsapp3");

                            b1.Property<string>("WhatsApp3Libelle")
                                .HasMaxLength(60)
                                .HasColumnType("character varying(60)")
                                .HasColumnName("whatsapp3_libelle");

                            b1.HasKey("TerrainId");

                            b1.ToTable("terrains");

                            b1.WithOwner()
                                .HasForeignKey("TerrainId")
                                .HasConstraintName("fk_terrains_terrains_id");
                        });

                    b.Navigation("Commodites");

                    b.Navigation("Commune");

                    b.Navigation("Contacts")
                        .IsRequired();

                    b.Navigation("Departement");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("Yakkomom.Models.Entities.TerrainPhoto", b =>
                {
                    b.HasOne("Yakkomom.Models.Entities.Terrain", "Terrain")
                        .WithMany("Photos")
                        .HasForeignKey("TerrainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_terrain_photos_terrains_terrain_id");

                    b.Navigation("Terrain");
                });

            modelBuilder.Entity("Yakkomom.Models.Entities.Localite", b =>
                {
                    b.Navigation("Enfants");
                });

            modelBuilder.Entity("Yakkomom.Models.Entities.Panorama", b =>
                {
                    b.Navigation("Hotspots");
                });

            modelBuilder.Entity("Yakkomom.Models.Entities.Service", b =>
                {
                    b.Navigation("Photos");
                });

            modelBuilder.Entity("Yakkomom.Models.Entities.Terrain", b =>
                {
                    b.Navigation("ClicsWhatsApp");

                    b.Navigation("Documents");

                    b.Navigation("Panoramas");

                    b.Navigation("Photos");
                });
#pragma warning restore 612, 618
        }
    }
}
